# require 'capistrano/setup'
# require 'capistrano/deploy'
# require 'capistrano/rbenv'
# require 'capistrano/rbenv_install'
# require 'capistrano/bundler'
# require 'capistrano/rails/assets'
# require 'capistrano/rails/migrations'
# require 'capistrano/nginx_unicorn'
# require 'capistrano/postgresql'
# require 'capistrano/sidekiq'
# require 'capistrano/rails/console'
# require 'capistrano-db-tasks'
# require 'capistrano/faster_assets'
# require 'rollbar/capistrano3'
# require 'whenever/capistrano'
# require 'airbrussh/capistrano'

# Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
