#!/usr/bin/env ruby

# Changes App name
require 'active_support/all'
app_name = ARGV.first
puts "Setting App name: #{app_name}..."
Dir.glob('**/*', File::FNM_DOTMATCH).reject{ |f| f['.git'] || f['script'] }.each do |name|
  if File.file?(name)
    out = File.read(name).gsub('rails-bootstrap', app_name)
    out = out.gsub('RailsBootstrap', app_name.gsub('-', '_').camelize)
    File.open(name, 'w+') do |f|
      f << out
    end
  end
end

# Removes Gitter and LICENSE
readme = File.read('README.md')
readme.gsub!(
  "[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Wolox" \
  "/rails-bootstrap?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_" \
  "content=badge)\n",
  ''
)
readme.gsub!(/\n\n## License((.)*(\n)*)*$/, '')
File.open('README.md', 'w') { |file| file.puts(readme) }
File.delete('LICENSE')

puts 'Done'
