#!/usr/bin/env bash

sed -i "/gem 'react-rails'/d" "Gemfile"
sed -re '$!N;/^\n$/!P;D' -i "Gemfile"
sed -i "s/gem 'webpacker'\(, '~> [0-9]\(\.[0-9]\(\.[0-9]\)\?\)\?'\)\?/&\n\ngem 'react-rails'/g" "Gemfile"
bundle install
rails webpacker:install:react
sed -i "s/body$/  = javascript_pack_tag 'application'\n  &/g" "app/views/layouts/application.html.slim"

exit 0
