#!/usr/bin/env ruby
# This script will setup all you need to start the server.

puts "== Installing dependencies =="
system "gem install bundler --no-ri --no-rdoc"
system "bundle check || bundle install -j 21"

puts "\n== Preparing database =="
system "bundle exec rake db:create db:migrate"

puts "\n== Removing old logs and tempfiles =="
system "rm -f log/*"
system "rm -rf tmp/*"
system "rm -rf coverage/*"
